Add rector [batch]
yiisoft/auth pull request #53
Opened 2022-09-27 13:49 UTC by xepozz

Added rector/rector to CI and composer.json. Mass creation refers to https://github.com/yiisoft/yii-dev-tool/pull/232

2023-06-21 15:34 UTC, samdark commented
Is this PR ready now?

2023-06-21 15:41 UTC, rustamwin commented
Yes.

2023-06-22 07:38 UTC, vjik requested changes

2023-06-22 07:38 UTC, vjik commented on composer.json
> +        "php": "^8.0",
Need changelog

2023-06-22 07:38 UTC, vjik commented on composer.json
> +        "rector/rector": "^0.14.3",
```suggestion
        "rector/rector": "^0.17",
```

2023-06-22 07:38 UTC, vjik commented on tests/Method/HttpBasicTest.php
> +            ->withAuthenticationCallback(fn (?string $username, ?string $password): ?IdentityInterface => $this->createIdentity(($username ?? 'null') . ':' . ($password ?? 'null')));
Suggest skip rector rule `ClosureToArrowFunctionRector` (see [example](https://github.com/yiisoft/package-template/blob/master/rector.php))

2023-06-26 04:35 UTC, merged