add "AuthenticationFailureHandler" and cleanup
yiisoft/auth pull request #9
Opened 2020-07-13 15:36 UTC by thenotsoft

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

2020-07-13 19:30 UTC, romkatsu requested changes

2020-07-13 19:30 UTC, romkatsu commented on src/Middleware/Auth.php
> +        ResponseFactoryInterface $responseFactory,
Property is used only in constructor

2020-07-14 05:50 UTC, xepozz commented on composer.json
> +        "phpunit/phpunit": "^9.2",
```suggestion
        "phpunit/phpunit": "^9.3",
```

2020-07-14 14:24 UTC, samdark approved these changes

2020-07-14 14:25 UTC, merged